services:
  postgres:
    image: postgres:16-alpine
    container_name: rl-postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: changeit
      POSTGRES_DB: rl_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: rl-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rl_db
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=changeit
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rl-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://app:8080
    depends_on:
      - app

volumes:
  postgres_data: