services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.dev
    container_name: rl-db-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  api:
    #build:
    #  context: ./api
    #  dockerfile: docker/Dockerfile.dev
    image: rl-jvm
    container_name: rl-api-dev
    env_file:
      - ./private/shared/secrets/.env
    environment:
      - POSTGRES_HOST=db
    #volumes:
    #  - ./api:/app
    depends_on:
      - db

  website:
    build:
      context: ./website
      dockerfile: Dockerfile.dev
    container_name: rl-website-dev
    env_file:
      - ./private/frontend/.env.local
      - ./private/shared/secrets/.env
    volumes:
      - ./website:/app
      - /app/node_modules # To preserve the node_modules folder
    depends_on:
      - api
  
  nginx:
    image: nginx:latest
    container_name: rl-nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - db
      - website