services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.dev
    container_name: rl-db-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  api:
    #build:
    #  context: ./api
    #  dockerfile: docker/Dockerfile.dev
    image: rl-jvm
    container_name: rl-api-dev
    env_file:
      - ./private/shared/secrets/.env
    environment:
      - POSTGRES_HOST=db
    ports:
      - "8080:8080"
    #volumes:
    #  - ./api:/app
    depends_on:
      - db

  website:
    build:
      context: ./website
      dockerfile: Dockerfile.dev
    container_name: rl-website-dev
    ports:
      - "3000:3000"
    env_file:
      - ./private/frontend/.env.local
      - ./private/shared/secrets/.env
    volumes:
      - ./website:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api