services:
  postgres:
    image: postgres
    container_name: rl-db-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dbuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeit}
      POSTGRES_DB: ${POSTGRES_DB:-rl_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  api:
    image: rl-jvm
    container_name: rl-api-dev
    environment:
      - DB_URL=jdbc:postgresql://localhost:5432/db
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  website:
    build:
      context: ./website
      dockerfile: Dockerfile.dev
    container_name: rl-website-dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://app:8080
      - NODE_ENV=development
    volumes:
      - ./website:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api

volumes:
  postgres_data_dev: 